### ISSUE TITLE
Any way to generate phonemes for lip sync animation?

### ISSUE THREAD

**Issue by sio-mchezo** [discordier/sam#45]
I'm not seeing a way

**Comment by discordier** [comment]
That totally depends on what you want to achieve.

In the end, we are generating speech from phonemes, you have to parse them the same as we do but instead of generating wave forms, you'd generate "lip forms".

As I have never done such, let alone know of any standardized format, I fear you are on your own with that.

**Comment by discordier** [comment]
Closing as this is beyond the scope of this project.
